### ISSUE TITLE
Jonathan Lin - Data Structure Challenge 1 - Individual Review Ticket

### ISSUE THREAD

**Issue by armarmgc** [armarmgc/group-m#8]
# Total score: 3.8
Individual score: 3
Team score: .8
Github pages: [Link](https://armarmgc.github.io/datastruct-proj/)
Team ticket: [Link](https://github.com/armarmgc/group-m/issues/7)

**Comment by dsblack0** [comment]
# Individual Score: 3/4

Describe Linked Lists, Describes Java Generic T
0/1 - no notes from tech talk 1 or anything described on github pages.

Queue Add and Delete
1/1 - comments included in code
1/1 - code running properly on replit to add to the queue
2/2 - code running properly on replit to delete from queue and has [individual implement](https://github.com/armarmgc/datastruct-proj/blob/master/chal1/Queue.java#L40)  of Delete

Merge 2 Queues
1/1 - comments included in code
2/2 - code running properly on replit to merge queues and has [individual implementation](https://github.com/armarmgc/datastruct-proj/blob/master/chal1/Queue.java#L73) of Merge method

Build Stack & Reverse Queue Order
1/2 - I was unable to find a full implementation of a stack but does have a [pop method](https://github.com/armarmgc/datastruct-proj/blob/master/chal1/Queue.java#L56)
1/1 - comments included in code and has [general purpose tester](https://github.com/armarmgc/datastruct-proj/blob/master/chal1/Queue.java#L187)
1/1 - reverse order test case running properly on replit

Overall
-1 check because although there are some notes and the running replit + code is included on github pages, there are no code snippets or decriptions of learning included.
